export const VALID_USERNAME = 'user';
export const VALID_ADMIN_USERNAME = 'admin';
export const VALID_PASSWORD = 'password';
export const ACCESSABLE_PROJECT = 'Project B';
export const LOCKED_PROJECT_ADMIN = 'Project B';
export const LOCKED_PROJECT = 'Project Dummy';
export const CORRECT_FILE_EXTENSION = '.mydsl';
export const WRONG_FILE_EXTENSION = '.wrong';
export const RESSOURCES = "./res/";
